# mundi_api
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module MundiApi
  # Card9 Model.
  class Card9 < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :last_four_digits

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :holder_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :holder_document

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :exp_month

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :exp_year

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :brand

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :type

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :label

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['last_four_digits'] = 'last_four_digits'
      @_hash['holder_name'] = 'holder_name'
      @_hash['holder_document'] = 'holder_document'
      @_hash['exp_month'] = 'exp_month'
      @_hash['exp_year'] = 'exp_year'
      @_hash['brand'] = 'brand'
      @_hash['type'] = 'type'
      @_hash['label'] = 'label'
      @_hash
    end

    def initialize(last_four_digits = nil,
                   holder_name = nil,
                   holder_document = nil,
                   exp_month = nil,
                   exp_year = nil,
                   brand = nil,
                   type = nil,
                   label = nil)
      @last_four_digits = last_four_digits
      @holder_name = holder_name
      @holder_document = holder_document
      @exp_month = exp_month
      @exp_year = exp_year
      @brand = brand
      @type = type
      @label = label
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      last_four_digits = hash['last_four_digits']
      holder_name = hash['holder_name']
      holder_document = hash['holder_document']
      exp_month = hash['exp_month']
      exp_year = hash['exp_year']
      brand = hash['brand']
      type = hash['type']
      label = hash['label']

      # Create object from extracted values.
      Card9.new(last_four_digits,
                holder_name,
                holder_document,
                exp_month,
                exp_year,
                brand,
                type,
                label)
    end
  end
end
