# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MundiApi
  # Request for capturing a charge
  class CreateCaptureChargeRequest < BaseModel
    # Code for the charge. Sending this field will update the code send on the
    # charge and order creation.
    # @return [String]
    attr_accessor :code

    # The amount that will be captured
    # @return [Integer]
    attr_accessor :amount

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['code'] = 'code'
      @_hash['amount'] = 'amount'
      @_hash
    end

    def initialize(code = nil,
                   amount = nil)
      @code = code
      @amount = amount
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      code = hash['code']
      amount = hash['amount']

      # Create object from extracted values.
      CreateCaptureChargeRequest.new(code,
                                     amount)
    end
  end
end
