# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MundiApi
  # Shipping data
  class CreateShippingRequest < BaseModel
    # Shipping amount
    # @return [Integer]
    attr_accessor :amount

    # Description
    # @return [String]
    attr_accessor :description

    # Recipient name
    # @return [String]
    attr_accessor :recipient_name

    # Recipient phone number
    # @return [String]
    attr_accessor :recipient_phone

    # The id of the address that will be used for shipping
    # @return [String]
    attr_accessor :address_id

    # Address data
    # @return [CreateAddressRequest]
    attr_accessor :address

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['amount'] = 'amount'
      @_hash['description'] = 'description'
      @_hash['recipient_name'] = 'recipient_name'
      @_hash['recipient_phone'] = 'recipient_phone'
      @_hash['address_id'] = 'address_id'
      @_hash['address'] = 'address'
      @_hash
    end

    def initialize(amount = nil,
                   description = nil,
                   recipient_name = nil,
                   recipient_phone = nil,
                   address_id = nil,
                   address = nil)
      @amount = amount
      @description = description
      @recipient_name = recipient_name
      @recipient_phone = recipient_phone
      @address_id = address_id
      @address = address
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      amount = hash['amount']
      description = hash['description']
      recipient_name = hash['recipient_name']
      recipient_phone = hash['recipient_phone']
      address_id = hash['address_id']
      address = CreateAddressRequest.from_hash(hash['address']) if
        hash['address']

      # Create object from extracted values.
      CreateShippingRequest.new(amount,
                                description,
                                recipient_name,
                                recipient_phone,
                                address_id,
                                address)
    end
  end
end
