# mundi_api
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module MundiApi
  # Subscription's split
  class CreateSubscriptionSplitRequest < BaseModel
    # Defines if the split is enabled
    # @return [Boolean]
    attr_accessor :enabled

    # Split
    # @return [List of CreateSplitRequest]
    attr_accessor :rules

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['enabled'] = 'enabled'
      @_hash['rules'] = 'rules'
      @_hash
    end

    def initialize(enabled = nil,
                   rules = nil)
      @enabled = enabled
      @rules = rules
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      enabled = hash['enabled']
      # Parameter is an array, so we need to iterate through it
      rules = nil
      unless hash['rules'].nil?
        rules = []
        hash['rules'].each do |structure|
          rules << (CreateSplitRequest.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      CreateSubscriptionSplitRequest.new(enabled,
                                         rules)
    end
  end
end
