# mundi_api
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module MundiApi
  # CreateEmvDataDukptDecryptRequest Model.
  class CreateEmvDataDukptDecryptRequest < BaseModel
    # Key serial number
    # @return [String]
    attr_accessor :ksn

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['ksn'] = 'ksn'
      @_hash
    end

    def initialize(ksn = nil)
      @ksn = ksn
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      ksn = hash['ksn']

      # Create object from extracted values.
      CreateEmvDataDukptDecryptRequest.new(ksn)
    end
  end
end
