# mundi_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'date'
module MundiApi
  # Contains the settings for creating a boleto payment
  class CreateBoletoPaymentRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Number of retries
    # @return [Integer]
    attr_accessor :retries

    # The bank code, containing three characters. The available codes are on the
    # API specification
    # @return [String]
    attr_accessor :bank

    # The instructions field that will be printed on the boleto.
    # @return [String]
    attr_accessor :instructions

    # Boleto due date
    # @return [DateTime]
    attr_accessor :due_at

    # Card's billing address
    # @return [CreateAddressRequest]
    attr_accessor :billing_address

    # The address id for the billing address
    # @return [String]
    attr_accessor :billing_address_id

    # Customer identification number with the bank
    # @return [String]
    attr_accessor :nosso_numero

    # Boleto identification
    # @return [String]
    attr_accessor :document_number

    # Boleto identification
    # @return [CreateInterestRequest]
    attr_accessor :interest

    # Boleto identification
    # @return [CreateFineRequest]
    attr_accessor :fine

    # Boleto identification
    # @return [Integer]
    attr_accessor :max_days_to_pay_past_due

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['retries'] = 'retries'
      @_hash['bank'] = 'bank'
      @_hash['instructions'] = 'instructions'
      @_hash['due_at'] = 'due_at'
      @_hash['billing_address'] = 'billing_address'
      @_hash['billing_address_id'] = 'billing_address_id'
      @_hash['nosso_numero'] = 'nosso_numero'
      @_hash['document_number'] = 'document_number'
      @_hash['interest'] = 'interest'
      @_hash['fine'] = 'fine'
      @_hash['max_days_to_pay_past_due'] = 'max_days_to_pay_past_due'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        due_at
        nosso_numero
        interest
        fine
        max_days_to_pay_past_due
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(retries = nil,
                   bank = nil,
                   instructions = nil,
                   billing_address = nil,
                   billing_address_id = nil,
                   document_number = nil,
                   due_at = SKIP,
                   nosso_numero = SKIP,
                   interest = SKIP,
                   fine = SKIP,
                   max_days_to_pay_past_due = SKIP)
      @retries = retries
      @bank = bank
      @instructions = instructions
      @due_at = due_at unless due_at == SKIP
      @billing_address = billing_address
      @billing_address_id = billing_address_id
      @nosso_numero = nosso_numero unless nosso_numero == SKIP
      @document_number = document_number
      @interest = interest unless interest == SKIP
      @fine = fine unless fine == SKIP
      @max_days_to_pay_past_due = max_days_to_pay_past_due unless max_days_to_pay_past_due == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      retries = hash.key?('retries') ? hash['retries'] : nil
      bank = hash.key?('bank') ? hash['bank'] : nil
      instructions = hash.key?('instructions') ? hash['instructions'] : nil
      billing_address = CreateAddressRequest.from_hash(hash['billing_address']) if
        hash['billing_address']
      billing_address_id =
        hash.key?('billing_address_id') ? hash['billing_address_id'] : nil
      document_number =
        hash.key?('document_number') ? hash['document_number'] : nil
      due_at = if hash.key?('due_at')
                 (DateTimeHelper.from_rfc3339(hash['due_at']) if hash['due_at'])
               else
                 SKIP
               end
      nosso_numero = hash.key?('nosso_numero') ? hash['nosso_numero'] : SKIP
      interest = CreateInterestRequest.from_hash(hash['interest']) if hash['interest']
      fine = CreateFineRequest.from_hash(hash['fine']) if hash['fine']
      max_days_to_pay_past_due =
        hash.key?('max_days_to_pay_past_due') ? hash['max_days_to_pay_past_due'] : SKIP

      # Create object from extracted values.
      CreateBoletoPaymentRequest.new(retries,
                                     bank,
                                     instructions,
                                     billing_address,
                                     billing_address_id,
                                     document_number,
                                     due_at,
                                     nosso_numero,
                                     interest,
                                     fine,
                                     max_days_to_pay_past_due)
    end

    def to_due_at
      DateTimeHelper.to_rfc3339(due_at)
    end
  end
end
