# mundi_api
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module MundiApi
  # CreateAntifraudRequest Model.
  class CreateAntifraudRequest < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :type

    # TODO: Write general description for this method
    # @return [CreateClearSaleRequest]
    attr_accessor :clearsale

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['type'] = 'type'
      @_hash['clearsale'] = 'clearsale'
      @_hash
    end

    def initialize(type = nil,
                   clearsale = nil)
      @type = type
      @clearsale = clearsale
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      type = hash['type']
      clearsale = CreateClearSaleRequest.from_hash(hash['clearsale']) if
        hash['clearsale']

      # Create object from extracted values.
      CreateAntifraudRequest.new(type,
                                 clearsale)
    end
  end
end
