# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'date'
require_relative 'get_transaction_response'

module MundiApi
  # Response object for getting a boleto transaction
  class GetBoletoTransactionResponse < GetTransactionResponse
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :url

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :bar_code

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :nosso_numero

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :bank

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :document_number

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :instructions

    # TODO: Write general description for this method
    # @return [GetBillingAddressResponse]
    attr_accessor :billing_address

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['url'] = 'url'
      @_hash['bar_code'] = 'bar_code'
      @_hash['nosso_numero'] = 'nosso_numero'
      @_hash['bank'] = 'bank'
      @_hash['document_number'] = 'document_number'
      @_hash['instructions'] = 'instructions'
      @_hash['billing_address'] = 'billing_address'
      @_hash = super().merge(@_hash)
      @_hash
    end

    def initialize(url = nil,
                   bar_code = nil,
                   nosso_numero = nil,
                   bank = nil,
                   document_number = nil,
                   instructions = nil,
                   billing_address = nil,
                   gateway_id = nil,
                   amount = nil,
                   status = nil,
                   success = nil,
                   created_at = nil,
                   updated_at = nil,
                   attempt_count = nil,
                   max_attempts = nil,
                   splits = nil,
                   next_attempt = nil,
                   transaction_type = nil)
      @url = url
      @bar_code = bar_code
      @nosso_numero = nosso_numero
      @bank = bank
      @document_number = document_number
      @instructions = instructions
      @billing_address = billing_address

      # Call the constructor of the base class
      super(gateway_id,
            amount,
            status,
            success,
            created_at,
            updated_at,
            attempt_count,
            max_attempts,
            splits,
            next_attempt,
            transaction_type)
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      url = hash['url']
      bar_code = hash['bar_code']
      nosso_numero = hash['nosso_numero']
      bank = hash['bank']
      document_number = hash['document_number']
      instructions = hash['instructions']
      billing_address = GetBillingAddressResponse.from_hash(hash['billing_address']) if
        hash['billing_address']
      gateway_id = hash['gateway_id']
      amount = hash['amount']
      status = hash['status']
      success = hash['success']
      created_at = DateTime.rfc3339(hash['created_at']) if hash['created_at']
      updated_at = DateTime.rfc3339(hash['updated_at']) if hash['updated_at']
      attempt_count = hash['attempt_count']
      max_attempts = hash['max_attempts']
      # Parameter is an array, so we need to iterate through it
      splits = nil
      unless hash['splits'].nil?
        splits = []
        hash['splits'].each do |structure|
          splits << (GetSplitResponse.from_hash(structure) if structure)
        end
      end
      next_attempt = DateTime.rfc3339(hash['next_attempt']) if
        hash['next_attempt']
      transaction_type = hash['transaction_type']

      # Create object from extracted values.
      GetBoletoTransactionResponse.new(url,
                                       bar_code,
                                       nosso_numero,
                                       bank,
                                       document_number,
                                       instructions,
                                       billing_address,
                                       gateway_id,
                                       amount,
                                       status,
                                       success,
                                       created_at,
                                       updated_at,
                                       attempt_count,
                                       max_attempts,
                                       splits,
                                       next_attempt,
                                       transaction_type)
    end
  end
end
