# mundi_api
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module MundiApi
  # GetWithdrawSourceResponse Model.
  class GetWithdrawSourceResponse < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :source_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['source_id'] = 'source_id'
      @_hash['type'] = 'type'
      @_hash
    end

    def initialize(source_id = nil,
                   type = nil)
      @source_id = source_id
      @type = type
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      source_id = hash['source_id']
      type = hash['type']

      # Create object from extracted values.
      GetWithdrawSourceResponse.new(source_id,
                                    type)
    end
  end
end
