# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'date'
module MundiApi
  # Response object for getting a period
  class GetPeriodResponse < BaseModel
    # TODO: Write general description for this method
    # @return [DateTime]
    attr_accessor :start_at

    # TODO: Write general description for this method
    # @return [DateTime]
    attr_accessor :end_at

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :id

    # TODO: Write general description for this method
    # @return [DateTime]
    attr_accessor :billing_at

    # TODO: Write general description for this method
    # @return [GetSubscriptionResponse]
    attr_accessor :subscription

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['start_at'] = 'start_at'
      @_hash['end_at'] = 'end_at'
      @_hash['id'] = 'id'
      @_hash['billing_at'] = 'billing_at'
      @_hash['subscription'] = 'subscription'
      @_hash
    end

    def initialize(start_at = nil,
                   end_at = nil,
                   id = nil,
                   billing_at = nil,
                   subscription = nil)
      @start_at = start_at
      @end_at = end_at
      @id = id
      @billing_at = billing_at
      @subscription = subscription
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      start_at = DateTime.rfc3339(hash['start_at']) if hash['start_at']
      end_at = DateTime.rfc3339(hash['end_at']) if hash['end_at']
      id = hash['id']
      billing_at = DateTime.rfc3339(hash['billing_at']) if hash['billing_at']
      subscription = GetSubscriptionResponse.from_hash(hash['subscription']) if
        hash['subscription']

      # Create object from extracted values.
      GetPeriodResponse.new(start_at,
                            end_at,
                            id,
                            billing_at,
                            subscription)
    end
  end
end
