# mundi_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MundiApi
  # Response object for getting an order item
  class GetOrderItemResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Id
    # @return [String]
    attr_accessor :id

    # Id
    # @return [Integer]
    attr_accessor :amount

    # Id
    # @return [String]
    attr_accessor :description

    # Id
    # @return [Integer]
    attr_accessor :quantity

    # Category
    # @return [String]
    attr_accessor :category

    # Code
    # @return [String]
    attr_accessor :code

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'id'
      @_hash['amount'] = 'amount'
      @_hash['description'] = 'description'
      @_hash['quantity'] = 'quantity'
      @_hash['category'] = 'category'
      @_hash['code'] = 'code'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(id = nil,
                   amount = nil,
                   description = nil,
                   quantity = nil,
                   category = nil,
                   code = nil)
      @id = id
      @amount = amount
      @description = description
      @quantity = quantity
      @category = category
      @code = code
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      id = hash.key?('id') ? hash['id'] : nil
      amount = hash.key?('amount') ? hash['amount'] : nil
      description = hash.key?('description') ? hash['description'] : nil
      quantity = hash.key?('quantity') ? hash['quantity'] : nil
      category = hash.key?('category') ? hash['category'] : nil
      code = hash.key?('code') ? hash['code'] : nil

      # Create object from extracted values.
      GetOrderItemResponse.new(id,
                               amount,
                               description,
                               quantity,
                               category,
                               code)
    end
  end
end
