# mundi_api
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

require_relative 'controller_test_base'

class InvoicesControllerTests < ControllerTestBase
  # Called only once for the class before any test has executed
  def self.startup
    self.controller = @@api_client.invoices
  end

  # Gets all invoices
  def test_test_get_invoices()
    # Parameters for the API call
    page = nil
    size = nil
    code = nil
    customer_id = nil
    subscription_id = nil
    created_since = nil
    created_until = nil
    status = nil
    due_since = nil
    due_until = nil
    customer_document = nil

    # Perform the API call through the SDK function
    result = self.class.controller.get_invoices(page, size, code, customer_id, subscription_id, created_since, created_until, status, due_since, due_until, customer_document)

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)

    # Test headers
    expected_headers = {}
    expected_headers['content-type'] = 'application/json'

    assert(TestHelper.match_headers(expected_headers, @response_catcher.response.headers))
  end

end
