# mundi_api
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

require_relative 'controller_test_base'

class SubscriptionsControllerTests < ControllerTestBase
  # Called only once for the class before any test has executed
  def self.startup
    self.controller = @@api_client.subscriptions
  end

  # Gets all subscriptions
  def test_test_get_subscriptions()
    # Parameters for the API call
    page = nil
    size = nil
    code = nil
    billing_type = nil
    customer_id = nil
    plan_id = nil
    card_id = nil
    status = nil
    next_billing_since = nil
    next_billing_until = nil
    created_since = nil
    created_until = nil

    # Perform the API call through the SDK function
    result = self.class.controller.get_subscriptions(page, size, code, billing_type, customer_id, plan_id, card_id, status, next_billing_since, next_billing_until, created_since, created_until)

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)

    # Test headers
    expected_headers = {}
    expected_headers['content-type'] = 'application/json'

    assert(TestHelper.match_headers(expected_headers, @response_catcher.response.headers))
  end

end
