# mundi_api
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

# CohesityManagementSdk
module MundiApi
  # All configuration including auth info and base URI for the API access
  # are configured in this class.
  class Configuration
    # The base Uri for API calls
    @base_uri = 'https://api.mundipagg.com/core/v1'

    @service_referer_name = 'TODO: Replace'

    # The username to use with basic authentication
    @basic_auth_user_name = 'TODO: Replace'

    # The password to use with basic authentication
    @basic_auth_password = 'TODO: Replace'

    # The proxy server to use for the request
    @proxy = nil

    # The attribute accessors for public properties.
    class << self
      attr_accessor :array_serialization, :base_uri, :service_referer_name, :basic_auth_user_name,
                    :basic_auth_password, :proxy
    end
  end
end
